### ISSUE TITLE
Add valon to website

### ISSUE THREAD

**Issue by ulpian** [Dodona/site#11]
Can we add Valon to our company website in the same way as we added our other members.

**Comment by donikajusufi** [comment]
Sure I'll work on it.

**Comment by donikajusufi** [comment]
Valon Ymeri 

![valonymeri](https://cloud.githubusercontent.com/assets/20597727/18665324/fd60f0e6-7f26-11e6-927d-29bbc4873a81.jpg)


The Software engineer. 
I work as a software engineer, I've built many applications, scripts and I have knowledge in both back-end and front-end. My job is my passion.

https://github.com/valonymeri

@ulpian can you please check this out ?

**Comment by ulpian** [comment]
Maybe a warmer photo would be good :)

**Comment by donikajusufi** [comment]
![slack for ios upload 2](https://cloud.githubusercontent.com/assets/20597727/18706857/f0feb11c-7ff3-11e6-821e-69ad10db636b.jpg)
![slack for ios upload 3](https://cloud.githubusercontent.com/assets/20597727/18706858/f0ffcd86-7ff3-11e6-8186-f4dc5ce362c4.jpg)

@ulpian Valon says he doesn't have many pictures so how about one of this two?

**Comment by ulpian** [comment]
@donikajusufi Maybe that first one with the yellow glasses :smile:

**Comment by donikajusufi** [comment]
@ulpian  I thought that one too  :) , okay I'll add him now .
