### ISSUE TITLE
Section on clients

### ISSUE THREAD

**Issue by ulpian** [Dodona/site#12]
We need a section on our website showing who we have worked with and built projects for, I am including a presentation file and jpg from one of our slides on our clientel.

![clients](https://cloud.githubusercontent.com/assets/1069533/18581334/04c27b2a-7bf8-11e6-9cd6-02dc940f0916.jpg)

You should be able to open the images within the windows presentation file;
[clients.pptx](https://github.com/Dodona/site/files/476508/clients.pptx)

I also include some additional logos below that we can add to the website;
**venue10**
![venue10](https://d1qb2nb5cznatu.cloudfront.net/startups/i/899398-33634115e810649c9fb352b1f8fb2f6d-medium_jpg.jpg?buster=1446550856)

**Loopcast**;
![loopcast](https://pbs.twimg.com/profile_images/574974316330160130/naCILgaZ.png)

**Comment by donikajusufi** [comment]
Yes I can open the pptx file , and I will start working on it.

**Comment by ulpian** [comment]
@donikajusufi The section of "our clients" needs to be just after "what we do"

**Comment by donikajusufi** [comment]
@ulpian  👍 I'll change it now.
